name: CI

on:
  push:
    branches:
      - 'main'
      - 'release-'

    tags: '*'

    paths-ignore:
      - 'docs/**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel intermediate builds: only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'lts'
          - '1'
        group:
          - symmetries
          - tensors
          - other
          - autodiff
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    uses: "QuantumKitHub/QuantumKitHubActions/.github/workflows/Tests.yml@main"
    with:
      group: "${{ matrix.group }}"
      julia-version: "${{ matrix.version }}"
      os: "${{ matrix.os }}"
      nthreads: 4
      timeout-minutes: 120
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test-nightly:
    needs: test
    strategy:
      matrix:
        version:
          - 'nightly'
        group:
          - symmetries
          - tensors
          - other
          - autodiff
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    uses: "QuantumKitHub/QuantumKitHubActions/.github/workflows/Tests.yml@main"
    with:
      group: "${{ matrix.group }}"
      julia-version: "${{ matrix.version }}"
      os: "${{ matrix.os }}"
      nthreads: 4
      timeout-minutes: 120
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
